const { exec } = require("child_process");
const express = require("express");
const fs = require("fs");
const cors = require("cors");
const app = express();

app.use(cors())

app.get("/", function (req, res) {
  const filePath = `datas/${req.query.landId}.json`;
  if (fs.existsSync(filePath)) {
    const file = fs.readFileSync(filePath);
    if (file) {
      const data = JSON.parse(file);
      if (data.features.length > 0) {
        return res.send(JSON.parse(file))
      }
    }
  }

  //console.log("No data, querying overpass")

  req.params.a;

  exec(
    getCommand(req.query.a, req.query.b, req.query.c, req.query.d, req.query.e, req.query.f, req.query.g, req.query.h, req.query.i, req.query.j, req.query.k, req.query.l, req.query.m, req.query.n),
    { maxBuffer: 1024 * 10000 },
    (error, stdout, stderr) => {
      if (error) {
        res.send(`error: ${error.message}`);
        return;
      }

      if (stderr) {
        res.send(`stderr: ${stderr}`);
        return;
      }
      fs.writeFileSync(filePath, stdout)

      res.send(stdout);
    }
  );
});

function getCommand(a, b, c, d, e, f, g, h, i, j, k, l, m, n) {
  return `
echo '/*
This has been generated by the overpass-turbo wizard.
The original search was:
“highway=*”
*/
[out:json][timeout:25];
// gather results
(
  node["amenity"](poly:"${a} ${b} ${c} ${d} ${e} ${f} ${g} ${h} ${i} ${j} ${k} ${l} ${m} ${n}");
  node["natural" = "tree"](poly:"${a} ${b} ${c} ${d} ${e} ${f} ${g} ${h} ${i} ${j} ${k} ${l} ${m} ${n}");
  node["highway"="street_lamp"](poly:"${a} ${b} ${c} ${d} ${e} ${f} ${g} ${h} ${i} ${j} ${k} ${l} ${m} ${n}");
  node["natural"="beach"](poly:"${a} ${b} ${c} ${d} ${e} ${f} ${g} ${h} ${i} ${j} ${k} ${l} ${m} ${n}");
  node["amenity"="fountain"](poly:"${a} ${b} ${c} ${d} ${e} ${f} ${g} ${h} ${i} ${j} ${k} ${l} ${m} ${n}");

  way["amenity"](poly:"${a} ${b} ${c} ${d} ${e} ${f} ${g} ${h} ${i} ${j} ${k} ${l} ${m} ${n}");
  way["building"](poly:"${a} ${b} ${c} ${d} ${e} ${f} ${g} ${h} ${i} ${j} ${k} ${l} ${m} ${n}");
  way["highway"](poly:"${a} ${b} ${c} ${d} ${e} ${f} ${g} ${h} ${i} ${j} ${k} ${l} ${m} ${n}");
  way["natural" = "water"](poly:"${a} ${b} ${c} ${d} ${e} ${f} ${g} ${h} ${i} ${j} ${k} ${l} ${m} ${n}");
  way["landuse"="forest"](poly:"${a} ${b} ${c} ${d} ${e} ${f} ${g} ${h} ${i} ${j} ${k} ${l} ${m} ${n}");
  way["leisure"="garden"](poly:"${a} ${b} ${c} ${d} ${e} ${f} ${g} ${h} ${i} ${j} ${k} ${l} ${m} ${n}");
  way["landuse"="greenfield"](poly:"${a} ${b} ${c} ${d} ${e} ${f} ${g} ${h} ${i} ${j} ${k} ${l} ${m} ${n}");
  way["leisure"="golf_course"](poly:"${a} ${b} ${c} ${d} ${e} ${f} ${g} ${h} ${i} ${j} ${k} ${l} ${m} ${n}");
  way["landuse"="grass"](poly:"${a} ${b} ${c} ${d} ${e} ${f} ${g} ${h} ${i} ${j} ${k} ${l} ${m} ${n}");
  way["natural"="grassland"](poly:"${a} ${b} ${c} ${d} ${e} ${f} ${g} ${h} ${i} ${j} ${k} ${l} ${m} ${n}");
  way["amenity"="grave_yard"](poly:"${a} ${b} ${c} ${d} ${e} ${f} ${g} ${h} ${i} ${j} ${k} ${l} ${m} ${n}");
  way["natural"="heath"](poly:"${a} ${b} ${c} ${d} ${e} ${f} ${g} ${h} ${i} ${j} ${k} ${l} ${m} ${n}");
  way["landuse"="meadow"](poly:"${a} ${b} ${c} ${d} ${e} ${f} ${g} ${h} ${i} ${j} ${k} ${l} ${m} ${n}");
  way["natural"="moor"](poly:"${a} ${b} ${c} ${d} ${e} ${f} ${g} ${h} ${i} ${j} ${k} ${l} ${m} ${n}");
  way["leisure"="nature_reserve"](poly:"${a} ${b} ${c} ${d} ${e} ${f} ${g} ${h} ${i} ${j} ${k} ${l} ${m} ${n}");
  way["landuse"="orchard"](poly:"${a} ${b} ${c} ${d} ${e} ${f} ${g} ${h} ${i} ${j} ${k} ${l} ${m} ${n}");
  way["leisure"="park"](poly:"${a} ${b} ${c} ${d} ${e} ${f} ${g} ${h} ${i} ${j} ${k} ${l} ${m} ${n}");
  way["leisure"="pitch"](poly:"${a} ${b} ${c} ${d} ${e} ${f} ${g} ${h} ${i} ${j} ${k} ${l} ${m} ${n}");
  way["landuse"="recreation_ground"](poly:"${a} ${b} ${c} ${d} ${e} ${f} ${g} ${h} ${i} ${j} ${k} ${l} ${m} ${n}");
  way["landuse"="village_green"](poly:"${a} ${b} ${c} ${d} ${e} ${f} ${g} ${h} ${i} ${j} ${k} ${l} ${m} ${n}");
  way["landuse"="vineyard"](poly:"${a} ${b} ${c} ${d} ${e} ${f} ${g} ${h} ${i} ${j} ${k} ${l} ${m} ${n}");
  way["natural"="wood"](poly:"${a} ${b} ${c} ${d} ${e} ${f} ${g} ${h} ${i} ${j} ${k} ${l} ${m} ${n}");
  way["natural"="water"](poly:"${a} ${b} ${c} ${d} ${e} ${f} ${g} ${h} ${i} ${j} ${k} ${l} ${m} ${n}");
  way["water"="lagoon"](poly:"${a} ${b} ${c} ${d} ${e} ${f} ${g} ${h} ${i} ${j} ${k} ${l} ${m} ${n}");
  way["water"="lakes"](poly:"${a} ${b} ${c} ${d} ${e} ${f} ${g} ${h} ${i} ${j} ${k} ${l} ${m} ${n}");
  way["water"="oxbow"](poly:"${a} ${b} ${c} ${d} ${e} ${f} ${g} ${h} ${i} ${j} ${k} ${l} ${m} ${n}");
  way["water"="rapids"](poly:"${a} ${b} ${c} ${d} ${e} ${f} ${g} ${h} ${i} ${j} ${k} ${l} ${m} ${n}");
  way["water"="river"](poly:"${a} ${b} ${c} ${d} ${e} ${f} ${g} ${h} ${i} ${j} ${k} ${l} ${m} ${n}");
  way["water"="stream"](poly:"${a} ${b} ${c} ${d} ${e} ${f} ${g} ${h} ${i} ${j} ${k} ${l} ${m} ${n}");
  way["water"="stream_pool"](poly:"${a} ${b} ${c} ${d} ${e} ${f} ${g} ${h} ${i} ${j} ${k} ${l} ${m} ${n}");
  way["water"="bassin"](poly:"${a} ${b} ${c} ${d} ${e} ${f} ${g} ${h} ${i} ${j} ${k} ${l} ${m} ${n}");
  way["water"="canal"](poly:"${a} ${b} ${c} ${d} ${e} ${f} ${g} ${h} ${i} ${j} ${k} ${l} ${m} ${n}");
  way["water"="ditch"](poly:"${a} ${b} ${c} ${d} ${e} ${f} ${g} ${h} ${i} ${j} ${k} ${l} ${m} ${n}");
  way["water"="drain"](poly:"${a} ${b} ${c} ${d} ${e} ${f} ${g} ${h} ${i} ${j} ${k} ${l} ${m} ${n}");
  way["water"="fish_pass"](poly:"${a} ${b} ${c} ${d} ${e} ${f} ${g} ${h} ${i} ${j} ${k} ${l} ${m} ${n}");
  way["water"="harbour"](poly:"${a} ${b} ${c} ${d} ${e} ${f} ${g} ${h} ${i} ${j} ${k} ${l} ${m} ${n}");
  way["water"="lock"](poly:"${a} ${b} ${c} ${d} ${e} ${f} ${g} ${h} ${i} ${j} ${k} ${l} ${m} ${n}");
  way["water"="moat"](poly:"${a} ${b} ${c} ${d} ${e} ${f} ${g} ${h} ${i} ${j} ${k} ${l} ${m} ${n}");
  way["water"="pound"](poly:"${a} ${b} ${c} ${d} ${e} ${f} ${g} ${h} ${i} ${j} ${k} ${l} ${m} ${n}");
  way["water"="reflection_pool"](poly:"${a} ${b} ${c} ${d} ${e} ${f} ${g} ${h} ${i} ${j} ${k} ${l} ${m} ${n}");
  way["water"="reservoir"](poly:"${a} ${b} ${c} ${d} ${e} ${f} ${g} ${h} ${i} ${j} ${k} ${l} ${m} ${n}");
  way["water"="wastewater"](poly:"${a} ${b} ${c} ${d} ${e} ${f} ${g} ${h} ${i} ${j} ${k} ${l} ${m} ${n}");
  way["natural"="mud"](poly:"${a} ${b} ${c} ${d} ${e} ${f} ${g} ${h} ${i} ${j} ${k} ${l} ${m} ${n}");
  way["natural"="wetland"](poly:"${a} ${b} ${c} ${d} ${e} ${f} ${g} ${h} ${i} ${j} ${k} ${l} ${m} ${n}");
  way["landluse"="sald_pound"](poly:"${a} ${b} ${c} ${d} ${e} ${f} ${g} ${h} ${i} ${j} ${k} ${l} ${m} ${n}");
  way["waterway"="river"](poly:"${a} ${b} ${c} ${d} ${e} ${f} ${g} ${h} ${i} ${j} ${k} ${l} ${m} ${n}");
  way["waterway"="canal"](poly:"${a} ${b} ${c} ${d} ${e} ${f} ${g} ${h} ${i} ${j} ${k} ${l} ${m} ${n}");
  way["waterway"="stream"](poly:"${a} ${b} ${c} ${d} ${e} ${f} ${g} ${h} ${i} ${j} ${k} ${l} ${m} ${n}");
  way["amenity"="college"](poly:"${a} ${b} ${c} ${d} ${e} ${f} ${g} ${h} ${i} ${j} ${k} ${l} ${m} ${n}");
  way["amenity"="hospital"](poly:"${a} ${b} ${c} ${d} ${e} ${f} ${g} ${h} ${i} ${j} ${k} ${l} ${m} ${n}");
  way["landuse"="residential"](poly:"${a} ${b} ${c} ${d} ${e} ${f} ${g} ${h} ${i} ${j} ${k} ${l} ${m} ${n}");
  way["landuse"="industrial"](poly:"${a} ${b} ${c} ${d} ${e} ${f} ${g} ${h} ${i} ${j} ${k} ${l} ${m} ${n}");
  way["landuse"="retail"](poly:"${a} ${b} ${c} ${d} ${e} ${f} ${g} ${h} ${i} ${j} ${k} ${l} ${m} ${n}");
  way["landuse"="education"](poly:"${a} ${b} ${c} ${d} ${e} ${f} ${g} ${h} ${i} ${j} ${k} ${l} ${m} ${n}");
  way["landuse"="farmland"](poly:"${a} ${b} ${c} ${d} ${e} ${f} ${g} ${h} ${i} ${j} ${k} ${l} ${m} ${n}");
  way["landuse"="farmyard"](poly:"${a} ${b} ${c} ${d} ${e} ${f} ${g} ${h} ${i} ${j} ${k} ${l} ${m} ${n}");
  way["landuse"="flowerbed"](poly:"${a} ${b} ${c} ${d} ${e} ${f} ${g} ${h} ${i} ${j} ${k} ${l} ${m} ${n}");
  way["landuse"="brownfield"](poly:"${a} ${b} ${c} ${d} ${e} ${f} ${g} ${h} ${i} ${j} ${k} ${l} ${m} ${n}");
  way["landuse"="garages"](poly:"${a} ${b} ${c} ${d} ${e} ${f} ${g} ${h} ${i} ${j} ${k} ${l} ${m} ${n}");
  way["landuse"="landfill"](poly:"${a} ${b} ${c} ${d} ${e} ${f} ${g} ${h} ${i} ${j} ${k} ${l} ${m} ${n}");
  way["landuse"="greenhouse_horticulture"](poly:"${a} ${b} ${c} ${d} ${e} ${f} ${g} ${h} ${i} ${j} ${k} ${l} ${m} ${n}");
  way["landuse"="quarry"](poly:"${a} ${b} ${c} ${d} ${e} ${f} ${g} ${h} ${i} ${j} ${k} ${l} ${m} ${n}");
  way["landuse"="railway"](poly:"${a} ${b} ${c} ${d} ${e} ${f} ${g} ${h} ${i} ${j} ${k} ${l} ${m} ${n}");
  way["landuse"="religious"](poly:"${a} ${b} ${c} ${d} ${e} ${f} ${g} ${h} ${i} ${j} ${k} ${l} ${m} ${n}");
  way["landuse"="village_green"](poly:"${a} ${b} ${c} ${d} ${e} ${f} ${g} ${h} ${i} ${j} ${k} ${l} ${m} ${n}");
  way["landuse"="grass"](poly:"${a} ${b} ${c} ${d} ${e} ${f} ${g} ${h} ${i} ${j} ${k} ${l} ${m} ${n}");
  way["amenity"="university"](poly:"${a} ${b} ${c} ${d} ${e} ${f} ${g} ${h} ${i} ${j} ${k} ${l} ${m} ${n}");
  way["amenity"="parking"](poly:"${a} ${b} ${c} ${d} ${e} ${f} ${g} ${h} ${i} ${j} ${k} ${l} ${m} ${n}");
  way["amenity"="school"](poly:"${a} ${b} ${c} ${d} ${e} ${f} ${g} ${h} ${i} ${j} ${k} ${l} ${m} ${n}");
  way["amenity"="bench"](poly:"${a} ${b} ${c} ${d} ${e} ${f} ${g} ${h} ${i} ${j} ${k} ${l} ${m} ${n}");
  way["amenity"="pharmacy"](poly:"${a} ${b} ${c} ${d} ${e} ${f} ${g} ${h} ${i} ${j} ${k} ${l} ${m} ${n}");
  way["amenity"="post_box"](poly:"${a} ${b} ${c} ${d} ${e} ${f} ${g} ${h} ${i} ${j} ${k} ${l} ${m} ${n}");
  way["amenity"="restaurant"](poly:"${a} ${b} ${c} ${d} ${e} ${f} ${g} ${h} ${i} ${j} ${k} ${l} ${m} ${n}");
  way["place"="square"](poly:"${a} ${b} ${c} ${d} ${e} ${f} ${g} ${h} ${i} ${j} ${k} ${l} ${m} ${n}");
  way["natural"="beach"](poly:"${a} ${b} ${c} ${d} ${e} ${f} ${g} ${h} ${i} ${j} ${k} ${l} ${m} ${n}");
  way["amenity"="fountain"](poly:"${a} ${b} ${c} ${d} ${e} ${f} ${g} ${h} ${i} ${j} ${k} ${l} ${m} ${n}");

  relation["amenity"="fountain"](poly:"${a} ${b} ${c} ${d} ${e} ${f} ${g} ${h} ${i} ${j} ${k} ${l} ${m} ${n}");
  relation["natural"="beach"](poly:"${a} ${b} ${c} ${d} ${e} ${f} ${g} ${h} ${i} ${j} ${k} ${l} ${m} ${n}");
  relation["place"="square"](poly:"${a} ${b} ${c} ${d} ${e} ${f} ${g} ${h} ${i} ${j} ${k} ${l} ${m} ${n}");
  relation["amenity"](poly:"${a} ${b} ${c} ${d} ${e} ${f} ${g} ${h} ${i} ${j} ${k} ${l} ${m} ${n}");
  relation["amenity"="restaurant"](poly:"${a} ${b} ${c} ${d} ${e} ${f} ${g} ${h} ${i} ${j} ${k} ${l} ${m} ${n}");
  relation["amenity"="post_box"](poly:"${a} ${b} ${c} ${d} ${e} ${f} ${g} ${h} ${i} ${j} ${k} ${l} ${m} ${n}");
  relation["amenity"="pharmacy"](poly:"${a} ${b} ${c} ${d} ${e} ${f} ${g} ${h} ${i} ${j} ${k} ${l} ${m} ${n}");
  relation["amenity"="bench"](poly:"${a} ${b} ${c} ${d} ${e} ${f} ${g} ${h} ${i} ${j} ${k} ${l} ${m} ${n}");
  relation["amenity"="school"](poly:"${a} ${b} ${c} ${d} ${e} ${f} ${g} ${h} ${i} ${j} ${k} ${l} ${m} ${n}");
  relation["amenity"="parking"](poly:"${a} ${b} ${c} ${d} ${e} ${f} ${g} ${h} ${i} ${j} ${k} ${l} ${m} ${n}");
  relation["amenity"="university"](poly:"${a} ${b} ${c} ${d} ${e} ${f} ${g} ${h} ${i} ${j} ${k} ${l} ${m} ${n}");
  relation["landuse"="grass"](poly:"${a} ${b} ${c} ${d} ${e} ${f} ${g} ${h} ${i} ${j} ${k} ${l} ${m} ${n}");
  relation["landuse"="village_green"](poly:"${a} ${b} ${c} ${d} ${e} ${f} ${g} ${h} ${i} ${j} ${k} ${l} ${m} ${n}");
  relation["landuse"="religious"](poly:"${a} ${b} ${c} ${d} ${e} ${f} ${g} ${h} ${i} ${j} ${k} ${l} ${m} ${n}");
  relation["landuse"="railway"](poly:"${a} ${b} ${c} ${d} ${e} ${f} ${g} ${h} ${i} ${j} ${k} ${l} ${m} ${n}");
  relation["landuse"="quarry"](poly:"${a} ${b} ${c} ${d} ${e} ${f} ${g} ${h} ${i} ${j} ${k} ${l} ${m} ${n}");
  relation["landuse"="greenhouse_horticulture"](poly:"${a} ${b} ${c} ${d} ${e} ${f} ${g} ${h} ${i} ${j} ${k} ${l} ${m} ${n}");
  relation["landuse"="landfill"](poly:"${a} ${b} ${c} ${d} ${e} ${f} ${g} ${h} ${i} ${j} ${k} ${l} ${m} ${n}");
  relation["natural"="water"](poly:"${a} ${b} ${c} ${d} ${e} ${f} ${g} ${h} ${i} ${j} ${k} ${l} ${m} ${n}");
  relation["water"="lagoon"](poly:"${a} ${b} ${c} ${d} ${e} ${f} ${g} ${h} ${i} ${j} ${k} ${l} ${m} ${n}");
  relation["water"="lakes"](poly:"${a} ${b} ${c} ${d} ${e} ${f} ${g} ${h} ${i} ${j} ${k} ${l} ${m} ${n}");
  relation["water"="oxbow"](poly:"${a} ${b} ${c} ${d} ${e} ${f} ${g} ${h} ${i} ${j} ${k} ${l} ${m} ${n}");
  relation["water"="rapids"](poly:"${a} ${b} ${c} ${d} ${e} ${f} ${g} ${h} ${i} ${j} ${k} ${l} ${m} ${n}");
  relation["water"="river"](poly:"${a} ${b} ${c} ${d} ${e} ${f} ${g} ${h} ${i} ${j} ${k} ${l} ${m} ${n}");
  relation["water"="stream"](poly:"${a} ${b} ${c} ${d} ${e} ${f} ${g} ${h} ${i} ${j} ${k} ${l} ${m} ${n}");
  relation["water"="stream_pool"](poly:"${a} ${b} ${c} ${d} ${e} ${f} ${g} ${h} ${i} ${j} ${k} ${l} ${m} ${n}");
  relation["water"="bassin"](poly:"${a} ${b} ${c} ${d} ${e} ${f} ${g} ${h} ${i} ${j} ${k} ${l} ${m} ${n}");
  relation["water"="canal"](poly:"${a} ${b} ${c} ${d} ${e} ${f} ${g} ${h} ${i} ${j} ${k} ${l} ${m} ${n}");
  relation["water"="ditch"](poly:"${a} ${b} ${c} ${d} ${e} ${f} ${g} ${h} ${i} ${j} ${k} ${l} ${m} ${n}");
  relation["water"="drain"](poly:"${a} ${b} ${c} ${d} ${e} ${f} ${g} ${h} ${i} ${j} ${k} ${l} ${m} ${n}");
  relation["water"="fish_pass"](poly:"${a} ${b} ${c} ${d} ${e} ${f} ${g} ${h} ${i} ${j} ${k} ${l} ${m} ${n}");
  relation["water"="harbour"](poly:"${a} ${b} ${c} ${d} ${e} ${f} ${g} ${h} ${i} ${j} ${k} ${l} ${m} ${n}");
  relation["water"="lock"](poly:"${a} ${b} ${c} ${d} ${e} ${f} ${g} ${h} ${i} ${j} ${k} ${l} ${m} ${n}");
  relation["water"="moat"](poly:"${a} ${b} ${c} ${d} ${e} ${f} ${g} ${h} ${i} ${j} ${k} ${l} ${m} ${n}");
  relation["water"="pound"](poly:"${a} ${b} ${c} ${d} ${e} ${f} ${g} ${h} ${i} ${j} ${k} ${l} ${m} ${n}");
  relation["water"="reflection_pool"](poly:"${a} ${b} ${c} ${d} ${e} ${f} ${g} ${h} ${i} ${j} ${k} ${l} ${m} ${n}");
  relation["water"="reservoir"](poly:"${a} ${b} ${c} ${d} ${e} ${f} ${g} ${h} ${i} ${j} ${k} ${l} ${m} ${n}");
  relation["water"="wastewater"](poly:"${a} ${b} ${c} ${d} ${e} ${f} ${g} ${h} ${i} ${j} ${k} ${l} ${m} ${n}");
  relation["natural"="mud"](poly:"${a} ${b} ${c} ${d} ${e} ${f} ${g} ${h} ${i} ${j} ${k} ${l} ${m} ${n}");
  relation["natural"="wetland"](poly:"${a} ${b} ${c} ${d} ${e} ${f} ${g} ${h} ${i} ${j} ${k} ${l} ${m} ${n}");
  relation["landluse"="sald_pound"](poly:"${a} ${b} ${c} ${d} ${e} ${f} ${g} ${h} ${i} ${j} ${k} ${l} ${m} ${n}");
  relation["waterway"="river"](poly:"${a} ${b} ${c} ${d} ${e} ${f} ${g} ${h} ${i} ${j} ${k} ${l} ${m} ${n}");
  relation["waterway"="canal"](poly:"${a} ${b} ${c} ${d} ${e} ${f} ${g} ${h} ${i} ${j} ${k} ${l} ${m} ${n}");
  relation["waterway"="stream"](poly:"${a} ${b} ${c} ${d} ${e} ${f} ${g} ${h} ${i} ${j} ${k} ${l} ${m} ${n}");
  relation["landuse"="forest"](poly:"${a} ${b} ${c} ${d} ${e} ${f} ${g} ${h} ${i} ${j} ${k} ${l} ${m} ${n}");
  relation["leisure"="garden"](poly:"${a} ${b} ${c} ${d} ${e} ${f} ${g} ${h} ${i} ${j} ${k} ${l} ${m} ${n}");
  relation["landuse"="greenfield"](poly:"${a} ${b} ${c} ${d} ${e} ${f} ${g} ${h} ${i} ${j} ${k} ${l} ${m} ${n}");
  relation["leisure"="golf_course"](poly:"${a} ${b} ${c} ${d} ${e} ${f} ${g} ${h} ${i} ${j} ${k} ${l} ${m} ${n}");
  relation["landuse"="grass"](poly:"${a} ${b} ${c} ${d} ${e} ${f} ${g} ${h} ${i} ${j} ${k} ${l} ${m} ${n}");
  relation["natural"="grassland"](poly:"${a} ${b} ${c} ${d} ${e} ${f} ${g} ${h} ${i} ${j} ${k} ${l} ${m} ${n}");
  relation["amenity"="grave_yard"](poly:"${a} ${b} ${c} ${d} ${e} ${f} ${g} ${h} ${i} ${j} ${k} ${l} ${m} ${n}");
  relation["natural"="heath"](poly:"${a} ${b} ${c} ${d} ${e} ${f} ${g} ${h} ${i} ${j} ${k} ${l} ${m} ${n}");
  relation["landuse"="meadow"](poly:"${a} ${b} ${c} ${d} ${e} ${f} ${g} ${h} ${i} ${j} ${k} ${l} ${m} ${n}");
  relation["natural"="moor"](poly:"${a} ${b} ${c} ${d} ${e} ${f} ${g} ${h} ${i} ${j} ${k} ${l} ${m} ${n}");
  relation["leisure"="nature_reserve"](poly:"${a} ${b} ${c} ${d} ${e} ${f} ${g} ${h} ${i} ${j} ${k} ${l} ${m} ${n}");
  relation["landuse"="orchard"](poly:"${a} ${b} ${c} ${d} ${e} ${f} ${g} ${h} ${i} ${j} ${k} ${l} ${m} ${n}");
  relation["leisure"="park"](poly:"${a} ${b} ${c} ${d} ${e} ${f} ${g} ${h} ${i} ${j} ${k} ${l} ${m} ${n}");
  relation["leisure"="pitch"](poly:"${a} ${b} ${c} ${d} ${e} ${f} ${g} ${h} ${i} ${j} ${k} ${l} ${m} ${n}");
  relation["landuse"="recreation_ground"](poly:"${a} ${b} ${c} ${d} ${e} ${f} ${g} ${h} ${i} ${j} ${k} ${l} ${m} ${n}");
  relation["landuse"="village_green"](poly:"${a} ${b} ${c} ${d} ${e} ${f} ${g} ${h} ${i} ${j} ${k} ${l} ${m} ${n}");
  relation["landuse"="vineyard"](poly:"${a} ${b} ${c} ${d} ${e} ${f} ${g} ${h} ${i} ${j} ${k} ${l} ${m} ${n}");
  relation["natural"="wood"](poly:"${a} ${b} ${c} ${d} ${e} ${f} ${g} ${h} ${i} ${j} ${k} ${l} ${m} ${n}");
  relation["building"]["type" = "multipolygon"](poly:"${a} ${b} ${c} ${d} ${e} ${f} ${g} ${h} ${i} ${j} ${k} ${l} ${m} ${n}");
  relation["highway"](poly:"${a} ${b} ${c} ${d} ${e} ${f} ${g} ${h} ${i} ${j} ${k} ${l} ${m} ${n}");
  relation["natural" = "water"](poly:"${a} ${b} ${c} ${d} ${e} ${f} ${g} ${h} ${i} ${j} ${k} ${l} ${m} ${n}");
  relation["landuse"="industrial"](poly:"${a} ${b} ${c} ${d} ${e} ${f} ${g} ${h} ${i} ${j} ${k} ${l} ${m} ${n}"); 
  relation["landuse"="residential"](poly:"${a} ${b} ${c} ${d} ${e} ${f} ${g} ${h} ${i} ${j} ${k} ${l} ${m} ${n}");
  relation["landuse"="retail"](poly:"${a} ${b} ${c} ${d} ${e} ${f} ${g} ${h} ${i} ${j} ${k} ${l} ${m} ${n}");
  relation["landuse"="education"](poly:"${a} ${b} ${c} ${d} ${e} ${f} ${g} ${h} ${i} ${j} ${k} ${l} ${m} ${n}");
  relation["amenity"="college"](poly:"${a} ${b} ${c} ${d} ${e} ${f} ${g} ${h} ${i} ${j} ${k} ${l} ${m} ${n}");
  relation["amenity"="hospital"](poly:"${a} ${b} ${c} ${d} ${e} ${f} ${g} ${h} ${i} ${j} ${k} ${l} ${m} ${n}");
  relation["landuse"="farmland"](poly:"${a} ${b} ${c} ${d} ${e} ${f} ${g} ${h} ${i} ${j} ${k} ${l} ${m} ${n}");
  relation["landuse"="farmyard"](poly:"${a} ${b} ${c} ${d} ${e} ${f} ${g} ${h} ${i} ${j} ${k} ${l} ${m} ${n}");
  relation["landuse"="flowerbed"](poly:"${a} ${b} ${c} ${d} ${e} ${f} ${g} ${h} ${i} ${j} ${k} ${l} ${m} ${n}");
  relation["landuse"="brownfield"](poly:"${a} ${b} ${c} ${d} ${e} ${f} ${g} ${h} ${i} ${j} ${k} ${l} ${m} ${n}");
  relation["landuse"="garages"](poly:"${a} ${b} ${c} ${d} ${e} ${f} ${g} ${h} ${i} ${j} ${k} ${l} ${m} ${n}");

);
// print results
out body;
>;
out skel qt;' | query-overpass`;
}

app.listen(3000);
